#!/usr/bin/env python3
"""KriszWheel puzzle-history reset marker frissítő.

Használat a repository gyökeréből:
    python tools/reset_puzzle_history.py

A script új reset azonosítót ír a data/puzzle-history-reset.json fájlba.
A játék a következő betöltéskor észleli ezt, törli a
kriszwheel.puzzle-history.v1 localStorage kulcsot, majd megjegyzi,
hogy az adott resetet már végrehajtotta.
"""

from __future__ import annotations

import json
import uuid
from datetime import datetime, timezone
from pathlib import Path


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    marker_path = root / "data" / "puzzle-history-reset.json"

    reset_id = uuid.uuid4().hex
    created_at = datetime.now(timezone.utc).isoformat(timespec="seconds")

    payload = {
        "resetId": reset_id,
        "createdAt": created_at,
        "description": (
            "Puzzle history reset marker generated by "
            "tools/reset_puzzle_history.py"
        ),
    }

    marker_path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    print("KriszWheel – Puzzle előzmény törlés előkészítve")
    print("=" * 47)
    print(f"Új reset azonosító: {reset_id}")
    print(f"Marker fájl: {marker_path}")
    print("")
    print(
        "A következő játékbetöltéskor a böngésző törli a korábbi "
        "feladvány-előzményt."
    )
    print(
        "Ha ezt más gépeken / böngészőkben is érvényesíteni szeretnéd, "
        "commitold ezt a marker fájlt is."
    )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
